image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y mysql-server
      sudo service mysql start
      mysql -u root -e "CREATE DATABASE wordpress;"
      wp core download --allow-root
      wp core config --dbname=wordpress --dbuser=root --dbpass= --dbhost=localhost --allow-root
      wp core install --url=localhost:8000 --title="WordPress Development" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --allow-root
    command: |
      sudo service mysql start
      wp server --allow-root --host=0.0.0.0
